Migrate dictionary merging to ansible native combine filter.
jtyr/ansible-pulp pull request #1
Opened 2016-12-01 03:59 UTC by sysadmind

This seems a bit cleaner to me. The `combine` filter is built into ansible and performs a similar operation to a python `dictionary.update()`. This removes the need to have 2 jinja variable substitutions. 
http://docs.ansible.com/ansible/playbooks_filters.html#combining-hashes-dictionaries

2016-12-01 10:21 UTC, jtyr requested changes

2016-12-01 10:21 UTC, jtyr commented on defaults/main.yaml
> +pulp_server_config: "{{ pulp_server_config__default |
Please could you format it like this?

```
pulp_server_config: "{{
  pulp_server_config__default |
  combine(pulp_server_config__custom) }}
```

The same in all other cases bellow.

2016-12-02 04:13 UTC, sysadmind commented
Updated per your request.

2016-12-02 11:05 UTC, jtyr requested changes

2016-12-02 11:05 UTC, jtyr commented on defaults/main.yaml
> +  combine(pulp_repo_auth_config__custom) }}"
Please keep the final empty line.

2016-12-04 19:20 UTC, sysadmind commented on defaults/main.yaml
> +  combine(pulp_repo_auth_config__custom) }}"
This file does still have a single blank line at the end. Git doesn't show it because it's expected to be there for all files. Do you want a second blank line at the end of the file?

2016-12-04 21:47 UTC, merged

2016-12-04 21:48 UTC, jtyr commented
Merged. Thanks for the PR, @sysadmind!